---
- name: Ensure required Zookeeper directories exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ zookeeper_data_dir }}",    owner: "{{ zookeeper_user }}", group: "{{ zookeeper_group }}" }
    - { path: "{{ zookeeper_datalog_dir }}", owner: "{{ zookeeper_user }}", group: "{{ zookeeper_group }}" }
    - { path: "{{ zookeeper_log_dir }}",     owner: "{{ zookeeper_user }}", group: "{{ zookeeper_group }}" }
    - { path: "{{ zookeeper_config_dir }}",  owner: root, group: root }
  tags: zk_config

- name: Write Zookeeper instance ID (myid)
  ansible.builtin.lineinfile:
    path: "{{ zookeeper_data_dir }}/myid"
    line: "{{ zookeeper_id }}"
    create: yes
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0644'
  tags: zk_config

- name: Apply Zookeeper environment file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ zookeeper_env_file }}"
    owner: root
    group: root
    mode: '0644'
  tags: zk_config

- name: Apply Zookeeper configuration
  ansible.builtin.template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_config_dir }}/zoo.cfg"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zookeeper
  tags: zk_config
